### ISSUE TITLE
Source Keeper Avoidance Fails to Find New Path

### ISSUE THREAD

**Issue by rougeayrn** [glitchassassin/screeps-cartographer#28]
A creep is trying to path long distance and also avoid source keepers, but runs into a case where it can't bypass the source keeper in room. Ideally, this should generate a completely new path using a different route, yeah?

In-room:
![image](https://user-images.githubusercontent.com/97561459/195968587-c43f0f53-1de6-4e5f-a3f7-2bb742fc1d1a.png)

Map:
![image](https://user-images.githubusercontent.com/97561459/195968563-4bdb5da1-fe16-4e2f-81e5-2437ae4f006d.png)

**Comment by glitchassassin** [comment]
All right - pushing out a provisional fix that adds *all* rooms adjacent to the route, if the creep is repathing because it's stuck. Give v1.3.11 a try and let me know if that resolves this issue.

**Comment by rougeayrn** [comment]
It doesn't look as if the changes respect `routeCallback`, which could lead to fallback routing choosing to path through an otherwise blocked out room, yeah?

Not respecting `routeCallback`:
https://github.com/glitchassassin/screeps-cartographer/blob/0ebd2fbecd080ef0d0d285c31b3f3327e8bf97c8/src/lib/WorldMap/findRoute.ts#L43

Potential solution:
`Object.values(Game.map.describeExits(route[i].room)).forEach(room => if (actualOpts.routeCallback?.(room, route[i].room) !== Infinity) rooms.add(room));`

**Comment by glitchassassin** [comment]
Good call. We're invoking that callback a lot, we can make it a bit more efficient. I'll have a fix ready shortly

**Comment by glitchassassin** [comment]
v1.3.12 pushed out

**Comment by rougeayrn** [comment]
Looks gorgeous to me! Will test when I get a chance.

**Comment by rougeayrn** [comment]
Mkay! So I updated to the most recent. Here's where we are at: It is trying to get to the "target" room from the "start" room. Originally, it tried the green path, realized it'd be stuck by a source keeper, and repathed (orange path) into the unexplored room to the north, realizing that it is not safe for measly 1M creeps. Upon the creep's replacement, it failed to find a path, spending a variable 2-7 CPU a tick. There is a cheap-ish path (blue line), but it's failing to find it. 
![image](https://user-images.githubusercontent.com/97561459/196831573-666ec887-9d96-4191-8a59-9543d5af95aa.png)

**Comment by glitchassassin** [comment]
https://user-images.githubusercontent.com/7684744/198312459-50d6a1dd-8651-4fca-98ba-a1b8970f77b9.mp4

Sample animation of expanding the rooms with floodfill

**Comment by glitchassassin** [comment]
Did some analysis with randomly-generated routes on a private server, just to check my theory. The heuristics to enhance findRoute do slightly increase CPU, but they also tend to find better paths than simple floodfill, so seem to be worth the effort.

**Comment by glitchassassin** [comment]
that is, heuristics + floodfill are better than just floodfill

**Comment by rougeayrn** [comment]
Thanks for the work on this issue! Will test and notify.

**Comment by glitchassassin** [comment]
Closing as no further issues reported
