### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by mkaulfers** [glitchassassin/screeps-cartographer#29]
Not 100% sure what caused this. I was able to snap a SS before it was "Poof". 

![image](https://user-images.githubusercontent.com/42121989/196054230-48861782-fa6a-4096-861c-bee63a97c1b6.png)

**Comment by glitchassassin** [comment]
Looks like `Game.map.describeExits` returned null because it didn't recognize the room from your creep's `creep.pos`. There's probably some condition in your code where `creep.pos.roomName` might not be a valid room. Not sure without seeing it.

**Comment by mkaulfers** [comment]
@glitchassassin yeh that's probably true, I'd say don't worry about looking into this one just yet. Rouge and I looked at it and we think we know a proper fix for it. We just placed it here for the sake of tracking purposes. We intend to isolate it and figure it out, if we get something from carto, we'll put up a PR. We haven't seen it since we did some cleanup so that's entirely possible.

**Comment by glitchassassin** [comment]
Sounds good!
