### ISSUE TITLE
Bug with creep fleeing

### ISSUE THREAD

**Issue by Alexey007gold** [glitchassassin/screeps-cartographer#37]
// move to any viable target square, if path is nearly done.
Above logic causes an issue when opts.flee is set to true.
Instead of making that last step to freedom the creep can be stuck in a vicious cycle of moving to a 'viable' square (which is actually closer to the object of fleeing), and then fleeing again

**Comment by glitchassassin** [comment]
relevant section: https://github.com/glitchassassin/screeps-cartographer/blob/3b02eaac8502cbac78c475f4db86a42952dd90cd/src/lib/Movement/moveTo.ts#L177

**Comment by glitchassassin** [comment]
drafting a fix in #38 but I don't have Screeps running at the moment to test it
