### ISSUE TITLE
Reconcile traffic and shoving should consult cost matrix for blocked positions

### ISSUE THREAD

**Issue by Alexey007gold** [glitchassassin/screeps-cartographer#44]
Issues caused by not consulting matrix
- creep can be shoved out of room (proven)
- can be shoved into a portal (haven't seen it, but very likely it's so)

Also I think if maxRooms is set to 1 we can block all border squares, so no accidental room leaving happens

**Comment by glitchassassin** [comment]
Added a test case to highlight this issue. Thinking through the best way to resolve it.
