### ISSUE TITLE
normalizeTargets misses the location right above the target

### ISSUE THREAD

**Issue by Boegie19** [glitchassassin/screeps-cartographer#51]
normalizeTargets breaks down as you can see with the RoomVisual for path finding target if on edge of room it or misses 1 location right above the target or that one does not get a visual

![image](https://github.com/glitchassassin/screeps-cartographer/assets/34578426/1b562b2a-e92a-4fe1-8e8a-5d55cf53005c)

**Comment by glitchassassin** [comment]
I've pushed up a fix that I believe addresses this. See if version 1.8.10 solves the issue.

**Comment by Boegie19** [comment]
Nop I targeted the extention in the middle and it now does it ontop of itself but not to above itself

**Comment by glitchassassin** [comment]
Hmm; I'm only seeing that behavior if I target the tile below:

![image](https://github.com/glitchassassin/screeps-cartographer/assets/7684744/23b03671-a25c-4e81-a4d0-ba7d53c90e67)

If I target a tile above the edge, with a range of 1, it correctly plots a path to all six positions:

![image](https://github.com/glitchassassin/screeps-cartographer/assets/7684744/bfe2de36-47b2-474f-8bfd-894be54d3a83)

**Comment by Boegie19** [comment]
You are right I put in the wrong number my mistake
